# Generated by Django 5.1.7 on 2025-04-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectname', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_type',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=True, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='upload_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
